'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const core=require('../assets/web-app.js'),env={window:{}};
for(const file of ['team-base','team-catalog','team-colors','team-stadiums','verified-locations'])vm.runInNewContext(read('assets/data/'+file+'.js'),env);
const teams=core.buildTeams(env.window),twice=core.buildTeams(env.window);
assert.equal(Object.keys(teams).length,620);
assert.equal(Object.values(teams).filter(t=>t.category==='NFL').length,32);
const count=x=>Object.values(x).reduce((n,t)=>n+t.chapters.length,0);
assert.equal(count(teams),count(twice),'Building twice does not mutate source arrays');
assert(Object.values(teams).filter(t=>t.category==='NFL').reduce((n,t)=>n+t.chapters.length,0)>2500);
for(const t of Object.values(teams)){assert(t.key&&t.display&&t.category);assert(Array.isArray(t.chapters));assert(env.window.FANMAP_TEAM_COLORS[t.key],t.key);}
assert.throws(()=>core.buildTeams({}));
assert.equal(core.safeURL('javascript:alert(1)'),'');assert.equal(core.safeURL('data:text/html,bad'),'');
assert.equal(core.safeURL('https://fanmap.com'),'https://fanmap.com/');
assert.equal(core.esc('<script>"&'), '&lt;script&gt;&quot;&amp;');
assert.equal(core.normal('São Paulo'),'sao paulo');
for(const p of [[null,null],[91,12],[0,181],['0',12],[Infinity,0]])assert.equal(core.validCoordinates(p),false);
assert.equal(core.validCoordinates([33.5,-112]),true);
const pin={id:'test-pin',teamKey:'arkansas',name:'Crew',note:'At the gate',date:'2026-10-10',lat:36.0678,lng:-94.1787};
assert(core.cleanPin(pin,teams));assert.equal(core.cleanPin({...pin,teamKey:'__proto__'},teams),null);
assert.equal(core.cleanPin({...pin,lat:Infinity},teams),null);assert.equal(core.cleanPin({...pin,name:' '},teams),null);
assert.equal(core.cleanPin({...pin,name:'x'.repeat(100)},teams).name.length,80);
assert.equal(core.listingStatus({verified:true}).kind,'listed','Legacy verified flag alone is not proof');
assert.equal(core.listingStatus({sourceVerification:'official-directory'}).kind,'checked');
assert.equal(core.listingStatus({sourceVerification:'official-directory',eventDate:'2020-01-01'},'2026-09-08').kind,'old');
assert.equal(core.namedVenue({venue:'Venue announced per game'}),false);
const reg={test:{name:'Old',start:[1,2],upcoming:{name:'New',start:[3,4],effectiveFrom:'2026-10-02'}}};
assert.equal(core.stadiumFor(reg,'test','2026-09-08').name,'Old');assert.equal(core.stadiumFor(reg,'test','2026-10-02').name,'New');
assert.equal(core.stadiumFor(reg,'__proto__'),null);assert.equal(core.stadiumFor({x:{start:[null,null]}},'x'),null);
const html=read('index.html');
assert(!/interactive preview|interactive demo|pilot|join early access|create preview profile/i.test(html));
for(const id of ['homeView','watchView','tailgateView','fanView','savedView'])assert(html.includes('id="'+id+'"'));
assert.equal(JSON.parse(read('site.webmanifest')).start_url,'/');
assert(read('app.html').includes("location.replace('/'"));assert(read('app/index.html').includes("location.replace('/'"));
assert(!read('assets/web-app.js').includes('sourceHTML'));
console.log('PASS: web core;',Object.keys(teams).length,'teams;',count(teams),'directory records; schema, URL safety, expiry, and redirects.');
